[package]
name = "simplecs_derive"
version = "0.1.0"
edition = "2024"
publish = true
description = "Procedural macros for the crate simplecs."
author = "Buzzac"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
